### PR TITLE
Resources: support TaskCanceledException handling for different .NET environment

### LINKED ISSUE #1002: [BUG] DNS record update failed with 504 after about 2min but no exception was thrown
**Describe the bug**
Sometimes ARM returns 504 Gateway Timeout after about 1-2min. However the library throws no exception so the caller is unable to know the operation actually fails.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Use Fiddler to inject **1min delay and 504 response** for DNS A record update request:

image

Exported Fiddler rules:

```
<?xml version="1.0" encoding="utf-8"?>
<AutoResponder LastSave="2020-03-11T13:04:20.1331365+08:00" FiddlerVersion="4.6.20171.26113">
  <State Enabled="true" Fallthrough="true" UseLatency="false">
    <ResponseRule Match="EXACT:https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/dnsZones/example.com/A/foobar?api-version=2018-03-01-preview" Action="*delay:60000" Enabled="true" />
    <ResponseRule Match="EXACT:https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/dnsZones/example.com/A/foobar?api-version=2018-03-01-preview" Action="C:\Users\work\Desktop\Response.txt" Enabled="true" />
  </State>
</AutoResponder>
```

Response file content(Response.txt):
```
HTTP/1.1 504 Gateway Timeout
Content-Type: application/json; charset=utf-8

{"error":{"details":[],"code":"GatewayTimeout"}}
```

Run the code.

Here is the mock scenario:

image

***Code Snippet***

```csharp
var creds = new AzureCredentialsFactory().FromServicePrincipal(
    "x", "x", "x",
    AzureEnvironment.AzureGlobalCloud);
var restClient = RestClient.Configure()
    .WithEnvironment(creds.Environment)
    .WithCredentials(creds)
    .Build();

// Use Fiddler proxy
restClient.RootHttpHandler.Proxy = new WebProxy("http://localhost:8888", true);
restClient.RootHttpHandler.UseProxy = true;
restClient.RootHttpHandler.ServerCertificateCustomValidationCallback = (HttpRequestMessage r, X509Certificate2 c, X509Chain ch, SslPolicyErrors e) =>
{
    return true;
};

var azure = Azure.Authenticate(restClient, creds.TenantId)
    .WithSubscription("x");

var zone = azure.DnsZones.GetById("/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/dnszones/example.com");
zone.Update()
    .DefineARecordSet("foobar")
    .WithIPv4Address("1.1.1.1")
    .Attach()
    .ApplyAsync().Wait();
```

**Expected behavior**
The library should throw an exception.

**Screenshots**

**Setup (please complete the following information):**
Windows
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
1.31.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by xccc-msft**
Fix #1002 
This was caused by the difference from dotnet frameworks when getting TaskCanceledException. For example, `netcoreapp2.0` will set task as `Faulted` while `net461` will set as `Canceled`.

### CODE REVIEW

File: src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs [hunk 1]
```diff
@@ -69,12 +69,15 @@ public Task<List<FluentModelTImpl>> CommitAndGetAllAsync(CancellationToken cance
                                 exceptions.Add(deleteTask.Exception);
                             }
                         }
+                        if (deleteTask.IsCanceled)
```
Comment (yungezz) [inline src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs]: curious, why specific to deleteTask

File: src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs [hunk 2]
```diff
@@ -69,12 +69,15 @@ public Task<List<FluentModelTImpl>> CommitAndGetAllAsync(CancellationToken cance
...
+                        {
+                            exceptions.Add(new TaskCanceledException());
```
Comment (ArchangelSDY) [inline src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs]: What's the difference between `IsFaulted` branch and `IsCanceled` branch?

File: src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs (hunk 1 above)
Comment (xccc-msft) [reply src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs]: Before execution, we will label all pending child tasks with `ToDelete`/`ToCreate`/`ToUpdate`. And this situation may happen at any of the pending tasks, not only limited by one kind of them.

File: src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs (hunk 2 above)
Comment (xccc-msft) [reply src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs]: When getting 504 error, for `isFaulted`, the task would have taskCanceledException inside. But for `isCanceled`, the task would have exception as null.

File: src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs (hunk 1 above)
Comment (ArchangelSDY) [inline src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs]: `else if` here?

Comment (xccc-msft) [reply src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs]: Updated. Thanks.

**Comment by weidongxu-microsoft** [comment]
Just a comment, make sure it works as expected when it is really being cancelled by the CancellationToken.
